###Nama         : Septavia Navis

###NIM 		     : 212410103039

###Kelas 	     : Kecerdasan Komputasional B


                                    Modul 1 Praktikum Data Mining

                                  Manipulasi array menggunakan numpy


#**KODE 1**

**f. Buatlah array 2D berikut menggunakan numpy**

      [4 4 5]

      [7 6 4]

      [9 7 4]

      [6 3 7]


**Jawab:**

In [ ]:
import numpy as np
arr = np.array([[4,4,5], [7,6,4], [9,7,4], [6,3,7]])
print(arr)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


**Penjelasan code:**

Array diatas dapat diakses menggunakan indeks baris dan kolom. Code diatas adalah array 2-dimensi yang berisi 4 baris 3 kolom. Setiap elemen array diatas dapat merepresentasikan sebuah angka bilangan bulat *integer* dengan nilai yang diberikan pada **nested list**.

**g. Buatlah array 3D berikut menggunakan numpy**

      [7 8 5] [2 1 2] [2 9 3]

      [4 7 7] [9 8 5] [2 4 8]

      [7 1 9] [3 7 3] [1 6 6]

      [5 4 10] [4 9 9] [8 1 3]

**Jawab:**

In [ ]:
arr = np.array([
[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],
[[2,1,2],[9,8,5],[3,7,3],[4,9,9],],
[[2,9,3],[2,4,8],[1,6,6],[8,1,3]]
])
print(arr)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


**Penjelasan code:**

Code diatas adalah array 3-dimensi yang memiliki 3 blok dengan masing-masing berisi 4 baris 3 kolom. Setiap elemen array diatas dapat merepresentasikan sebuah angka bilangan bulat *integer*. Dalam code diatas terdapat function ***np.array()*** untuk mendefinisikan sebuah array dengan nama variable ***arr***. Setelah variable ***arr*** didefinisikan, terdapat perintah ***print(arr)*** yang mana untuk mengeksekusi array yang tersedia.

#**KODE 2**

**d. Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka 
2 pada setiap bilangan di kolom genap array berikut.**


      [1 8 8 2]

      [8 2 1 2]

      [10 1 4 7]

      [1 4 7 8]

      [8 2 3 4]

**Jawab:**

In [ ]:
arr = np.array([
[1,8,8,2],
[8,2,1,2],
[10,1,4,7],
[1,4,7,8],
[8,2,3,4]
])

arr[::2, :] +=1
arr[:, 1::2] +=2
print(arr)

[[ 2 11  9  5]
 [ 8  4  1  4]
 [11  4  5 10]
 [ 1  6  7 10]
 [ 9  5  4  7]]


**Penjelasan code:**

Code diatas adalah array 2-dimensi yang berisi 5 baris 4 kolom. Terdapat 2 operasi pada array diatas yang nantinya akan dijalankan secara bersamaan, diantaranya:
- **arr[::2, :] +=1**

  function diatas berfungsi untuk  menambahkan nilai 1 pada setiap elemen yang ada pada baris dengan indeks genap [0,2,4]

- **arr[:, 1::2] +=2**

  function diatas berfungsi untuk menambahkan nilai 2 pada setiap elemen yang ada pada kolom dengan indeks ganjil [1,3]

Ketika kedua operasi dijalankan, maka baris akan bertambah 1 dan kolom akan bertambah 2.

**e. Baliklah sumbu z array 3D berikut**

      [7 8 5] [2 1 2] [2 9 3]

      [4 7 7] [9 8 5] [2 4 8]

      [7 1 9] [3 7 3] [1 6 6]

      [5 4 10] [4 9 9] [8 1 3]


**Jawab:**

In [ ]:
arr = np.array([
[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],
[[2,1,2],[9,8,5],[3,7,3],[4,9,9],],
[[2,9,3],[2,4,8],[1,6,6],[8,1,3]]
])
print(arr[::-1]) #mengubah urutan

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


**Penjelasan code:**

Code diatas adalah array 3-dimensi. Didalam array tersebut terdapat function atau perintah ***arr[::-1]*** untuk merepresentasikan membalikkan atau mengubah urutan indeks blok secara vertikal pada array. Secara lebih jelasnya adalah untuk indeks pada blok 2 nanti akan berada diatas, indeks pada blok 1 tetap berada ditengah, dan indeks pada blok 0 akan berada dibawah.

**f. Ubahlah array pada soal e menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah reshape)**

**Jawab:**

In [ ]:
arr = np.array([
    [[7,8,5], [4,7,7], [7,1,9], [5,4,10]], 
    [[2,1,2], [9,8,5], [3,7,3], [4,9,9]], 
    [[2,9,3], [2,4,8], [1,6,6], [8,1,3]]
    ])
print(arr.shape)
print(np.reshape(arr, (6,6)))

(3, 4, 3)
[[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


**Penjelasan code:**

Code diatas merupakan array 3-dimensi. Terdapat 2 function, diantaranya:

- ***np.reshape()*** pada array **arr** yang berfungsi untuk mengubah dimensi sesuai keinginan kita.

- ***arr.shape*** pada array **arr** berfungsi untuk menentukan bentuk **x** **y** **z** pada blok array.

Pada penentuan awal berbentuk (3,4,3), yaitu 3 kolom, 4 baris, 3 kolom. Kemudian setelah menggunakan perintah **reshape()** dan parameter (6,6) maka array **arr** akan diubah menjadi array 2-dimensi dengan ukuran (6,6).

Setelah bentuk awal diubah, elemen array akan disusun menjadi bentuk baru dengan 6 baris dan 6 kolom dengan cara mengambil setiap elemen secara berurutan dari array awal. Pengambilan ini dimulai dari elemen pertama hingga terakhir.

**Noted:** Untuk perintah **reshape()** jumlah elemen array awal = jumlah elemen array baru.

#**KODE 3**

**e. Ubahlah matris kiri menjadi matriks sebelah kanan**

      [5 10 10 7]         [9 3 1 8]

      [7 8 4 10]          [5 2 6 10]

      [9 10 2 5]          [9 4 4 6]

      [1 8 9 3]           [10 7 5 10]

      [6 10 5 2]          [4 10 7 8]

      [4 6 9 4]           [2 5 9 10]


**Jawab:**

In [ ]:
arr = np.array([
[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]
])

array = np.array_split(arr,2,axis=1)[::-1]
arrays = np.concatenate(array, axis=1)

x = np.array_split(arrays,2,axis=0)[::-1]
x1 = np.concatenate(x,axis=0)
print(x1)

[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]


**Penjelasan code:**

Dalam code diatas terdapat beberapa operasi, diantaranya:

- ***np.array_split()***, digunakan untuk membagi array. Terdapat parameter **(arr,2)** yang mana untuk membagi array menjadi 2 bagian. Parameter **(axis=1)** berguna untuk membagi array berdasarkan sumbu kolom. Lalu perintah **[::-1]** untuk membalikkan array. Hasilnya adalah array dengan 2 elemen yang masing-masing elemen adalah array 6x2.

- ***np.concatenate(array, axis=1)***, digunakan untuk menggabung 2 array menjadi array 6x4.

- ***np.array_split()***, digunakan untuk membagi array. Terdapat parameter **(array,2)** yang mana untuk membagi array menjadi 2 bagian. Parameter **(axis=0)** berguna untuk membagi array berdasarkan sumbu baris. Lalu perintah **[::-1]** untuk membalikkan array. Hasilnya adalah array dengan 2 elemen yang masing-masing elemen adalah array 3x4.

- ***np.concatenate(x,axis=0)***, digunakan untuk menggabungkan 2 array menjadi array 6x4.

- Kemudian setelah menjalankan operasi-operasi diatas, ada perintah **print(x1)** untuk mengeksekusi penggabugan array pada perintah **concatenate**